language: python

python:
  - "3.4" # micropython version

install:
  - pip install pytest
  - cd src

stages:
  - test

jobs:
  include:
    - stage: "test"
      name: "Pytest"
      script: python3 -m pytest tests/
    - stage: "test"
      name: "test_frag_new"
      script: python3 test_frag_new.py
